Quora_Copy/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :answers
  resources :topics
  resources :questions do
    collection do
      post 'follow'
    end
  end
  resources :users
  root to: "questions#index"

end

Quora_Copy/app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers, dependent: :destroy
	belongs_to :user
	belongs_to :topic
	validates :name, presence: true
end

Quora_Copy/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @answer = Answer.where(question_id: @question.id)
  end

  # GET /questions/new
  def new
    @question = current_user.questions.build
  end

  def follow
    # binding.pry
    user_id = current_user.id.to_i
    if params[:question][:user_id].present?
      f_users = current_user.following_users
      respond_to do |format|
        if f_users.include?(user_id)
          f_users.delete(user_id)
          current_user.save
          format.html { redirect_to :back, notice: 'User Unfollowed' }
        else
          f_users << user_id
          current_user.save
          format.html { redirect_to :back, notice: 'User Followed' }
        end
      end
    else
      topic = Topic.find(params[:question][:topic_id].to_i)
      respond_to do |format|
        if topic.following_users.include?(user_id)
          topic.following_users.delete(user_id)
          topic.save
          format.html { redirect_to :back, notice: 'Topic Unfollowed' }
        else
          topic.following_users. << user_id
          topic.save
          format.html { redirect_to :back, notice: 'Topic Followed' }
        end
      end
    end
  end

  # def follow_topic
  #   binding.pry
  #   f_users = current_user.topics.following_users
  #   user_id = current_user.id.to_i
  #   respond_to do |format|
  #     if f_users.include?(user_id)
  #       f_users.delete(user_id)
  #       current_user.save
  #       format.html { redirect_to :back, notice: 'Topic Unfollowed' }
  #     else
  #       f_users << user_id
  #       current_user.save
  #       format.html { redirect_to :back, notice: 'Topic Followed' }
  #     end
  #   end 
  # end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.build(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.fetch(:question, {}).permit(:name,:topic_id)
    end
end

Quora_Copy/app/helpers/questions_helper.rb
module QuestionsHelper
end

Quora_Copy/app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
<p>
  <%= f.text_area :name, placeholder: "Enter Question" %>
</p>
<p>
  <%= f.label :select_topic %>
  <%= f.collection_select :topic_id, Topic.all, :id, :name, include_blank: false%>
</p>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Quora_Copy/app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

Quora_Copy/app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Questions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th>Question</th>
      <th>Topic</th>
      <th>Author</th>
      <th colspan="3">Actions</th>
    </tr>
    <% if @questions.count == 0 %>
      <tr>
        <td colspan="5">No Item Found</td>
      </tr>
    <% else %>
      <% @questions.each do |question| %>
        <tr>
          <td><%= question.name %></td>
          <td><%= question.topic.name %></td>
          <td><%= question.user.email %></td>
          <td><%= link_to 'Show', question %></td>
          <td><%= link_to 'Edit', edit_question_path(question) %></td>
          <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>
<br>

<%= link_to 'Add New Question', new_question_path %>
<%= link_to 'Add New Topic', new_topic_path %>

Quora_Copy/app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

Quora_Copy/app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<h2>User: <%= @question.user.email %></h2>
<%= form_for('question', :url => {action: 'follow'}) do |f| %>
	<%= f.text_field :user_id, value: @question.user_id, hidden: true %>
	<%= f.submit 'Follow User' %>
<% end %>
<h2>Topic: <%= @question.topic.name %></h2>
<%= form_for('question', :url => {action: 'follow'}) do |f| %>
	<%= f.text_field :topic_id, value: @question.topic_id, hidden: true %>
	<%= f.submit 'Follow Topic' %>
<% end %>
Question: <%= @question.name %>
<div>
	Answers: 
	<p>
		<ol>
			<% @answer.each do |ans| %>
	          <li><%= ans.name %></li>
	        <% end %>
      	</ol>
    </p>
    <p>
      <%= form_for(Answer.new) do |f| %>
		<p>
		  <%= f.text_field :question_id, hidden: true, value: @question.id %>
		  <%= f.text_area :name, placeholder: "Enter Answer" %>
		</p>
		  <% if Answer.new.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(Answer.new.errors.count, "error") %> prohibited this question from being saved:</h2>

		      <ul>
		      <% Answer.new.errors.full_messages.each do |message| %>
		        <li><%= message %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>

		  <div class="actions">
		    <%= f.submit %>
		  </div>
		<% end %>
	</p>
</div>
<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>